<a href="https://colab.research.google.com/github/Jangala-Megha-Harsha/AIML-2025/blob/main/Lab01_AIML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Lab01- Implement basic data structures of Numpy, Pandas, Matplotlib and Access Data from sources**

# Part 01: Lab Task is implement the following data structures using Numpy and Pandas.

In [ ]:
import numpy as np
List1 = [1, 2, 3]
array1 = np.array(List1)
array1

array([1, 2, 3])

In [ ]:
type(List1)

list

In [ ]:
type(array1)

numpy.ndarray

**Perform Mathematical Operations on these datasets - Multiplication, Division, Poweroff**

In [ ]:
List2 = [3, 2, 1]
array2 = np.array(List2)
array2

array([3, 2, 1])

In [ ]:
print("array2 Multiplied by array1: ", array2 * array1)
print("array2 Divided by array1: ", array2 / array1)
print(f"array2 raised to the Power of array1: {array2 ** array1}")
print(f"{array2} raised to the Power of {array1}: {array2 ** array1}")

array2 Multiplied by array1:  [3 4 3]
array2 Divided by array1:  [3.         1.         0.33333333]
array2 raised to the Power of array1: [3 4 1]
[3 2 1] raised to the Power of [1 2 3]: [3 4 1]


In [13]:
# sine function
print("Sine of array1: ",np.sin(array1))
print("Sine of array2: ",np.sin(array2))
# Cosine function
print("Cosine of array1: ", np.cos(array1))
print("Cosine of array2: ", np.cos(array2))
# logarithm
print("Natural logarithm: ",np.log(array1))
print("Base-10 logarithm: ",np.log10(array1))
print("Base-2 logarithm: ",np.log2(array1))
# Exponential
print("Exponential: ",np.exp(array1))

Sine of array1:  [0.84147098 0.90929743 0.14112001]
Sine of array2:  [0.14112001 0.90929743 0.84147098]
Cosine of array1:  [ 0.54030231 -0.41614684 -0.9899925 ]
Cosine of array2:  [-0.9899925  -0.41614684  0.54030231]
Natural logarithm:  [0.         0.69314718 1.09861229]
Base-10 logarithm:  [0.         0.30103    0.47712125]
Base-2 logarithm:  [0.        1.        1.5849625]
Exponential:  [ 2.71828183  7.3890561  20.08553692]


In [14]:
print("Adding two numpy arrays {array1} and {array2} together:", array1+array2)
print(f"Adding two numpy arrays {array1} and {array2} together: {array1+array2}")

Adding two numpy arrays {array1} and {array2} together: [4 4 4]
Adding two numpy arrays [1 2 3] and [3 2 1] together: [4 4 4]
